CREATE TABLE tbdepartamentos (
departamento_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
nombre_dept     VARCHAR2(50) NOT NULL,
abreviatura		VARCHAR2(5) NOT NULL,
ubicacion       VARCHAR2(100),
    -- Definición de la Llave Primaria
    CONSTRAINT pk_departamentos PRIMARY KEY (departamento_id)
);
 
CREATE TABLE tbempleados (
    empleado_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre          VARCHAR2(50) NOT NULL,
    apellido        VARCHAR2(50) NOT NULL,
    email           VARCHAR2(100) UNIQUE,
    fecha_ingreso   DATE DEFAULT SYSDATE,
    salario         NUMBER(8,2),
    departamento_id NUMBER,
    -- Definición de Llaves Primarias y Foráneas
    CONSTRAINT pk_empleados PRIMARY KEY (empleado_id),
    CONSTRAINT fk_empleados_dept FOREIGN KEY (departamento_id) 
        REFERENCES tbdepartamentos(departamento_id)
        ON DELETE SET NULL
);

-- Tabla para definir los roles e itinerarios de permisos
CREATE TABLE tbroles (
    rol_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre_rol    VARCHAR2(50) NOT NULL UNIQUE,
    descripcion   VARCHAR2(200),
    CONSTRAINT pk_roles PRIMARY KEY (rol_id)
);

-- Tabla para las credenciales y estado del usuario
CREATE TABLE tbusuarios (
    usuario_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username       VARCHAR2(50) NOT NULL UNIQUE,
    password_hash  VARCHAR2(255) NOT NULL,
    estado         VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    empleado_id    NUMBER UNIQUE,
    rol_id         NUMBER NOT NULL,
    fecha_creacion DATE DEFAULT SYSDATE,
    -- Definición de Llaves Primarias y Foráneas
    CONSTRAINT pk_usuarios PRIMARY KEY (usuario_id),
    CONSTRAINT fk_usuarios_empleado FOREIGN KEY (empleado_id) 
        REFERENCES tbempleados(empleado_id) 
        ON DELETE CASCADE,
    CONSTRAINT fk_usuarios_rol FOREIGN KEY (rol_id) 
        REFERENCES tbroles(rol_id)
);

-- 1. Insertar Departamentos
INSERT INTO tbdepartamentos (nombre_dept, abreviatura, ubicacion) 
VALUES ('Tecnología de la Información', 'IT', 'Edificio A - Piso 3');

INSERT INTO tbdepartamentos (nombre_dept, abreviatura, ubicacion) 
VALUES ('Recursos Humanos', 'RRHH', 'Edificio B - Piso 1');

INSERT INTO tbdepartamentos (nombre_dept, abreviatura, ubicacion) 
VALUES ('Finanzas', 'FIN', 'Edificio A - Piso 2');

-- 2. Insertar Roles
INSERT INTO tbroles (nombre_rol, descripcion) 
VALUES ('ROLE_ADMIN', 'Acceso total al sistema y configuraciones');

INSERT INTO tbroles (nombre_rol, descripcion) 
VALUES ('ROLE_USER', 'Acceso estándar de lectura y operaciones básicas');

INSERT INTO tbroles (nombre_rol, descripcion) 
VALUES ('ROLE_MANAGER', 'Acceso a reportes y aprobación de procesos');

-- 3. Insertar Empleados (vinculados a Departamentos 1, 2 y 3)
INSERT INTO tbempleados (nombre, apellido, email, fecha_ingreso, salario, departamento_id) 
VALUES ('Carlos', 'Gómez', 'carlos.gomez@empresa.com', TO_DATE('2023-01-15', 'YYYY-MM-DD'), 2500.00, 1);

INSERT INTO tbempleados (nombre, apellido, email, fecha_ingreso, salario, departamento_id) 
VALUES ('Ana', 'Martínez', 'ana.martinez@empresa.com', TO_DATE('2023-03-20', 'YYYY-MM-DD'), 1800.00, 2);

INSERT INTO tbempleados (nombre, apellido, email, fecha_ingreso, salario, departamento_id) 
VALUES ('Luis', 'Hernández', 'luis.hernandez@empresa.com', TO_DATE('2023-06-10', 'YYYY-MM-DD'), 3100.00, 3);

-- 4. Insertar Usuarios (vinculados a Empleados y Roles)
-- La contraseña encriptada equivale a '123456' en BCrypt
INSERT INTO tbusuarios (username, password_hash, estado, empleado_id, rol_id, fecha_creacion) 
VALUES ('cgomez', '$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqv139e', 'ACTIVO', 1, 1, SYSDATE);

INSERT INTO tbusuarios (username, password_hash, estado, empleado_id, rol_id, fecha_creacion) 
VALUES ('amartinez', '$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqv139e', 'ACTIVO', 2, 2, SYSDATE);

INSERT INTO tbusuarios (username, password_hash, estado, empleado_id, rol_id, fecha_creacion) 
VALUES ('lhernandez', '$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqv139e', 'INACTIVO', 3, 3, SYSDATE);

COMMIT;

--Tendrán la clave 123456
UPDATE tbusuarios
SET password_hash = '$2a$10$GQxGH.TTMVgcEsO/CeCEb.PmqJegafuYXpLvm2SHxf7xfnS.TEcUq'
WHERE username IN ('amartinez', 'lhernandez');

COMMIT;

--Tendrán la clave 1234
UPDATE tbusuarios
SET password_hash = '$2a$10$Wd1QwCCopDgLjTM0UJQ.3Ox6VGS/qacSKSW.Mr6gL2JSkCNeUYuRy'
WHERE username = 'cgomez';

COMMIT;